### ISSUE TITLE
Cidadao.telefone - tamanho de campo no banco - aumentar

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/sermilweb#19]
O campo telefone na tabela cidadao precisa aumentar para 11 digitos para comportar as mudancas que as empresas de telefone fizeram nos ultimos tempos.

**Comment by 6975usa** [comment]
Ex: (11) 99852-5225 - Celular em SP
Total de 11 digitos

**Comment by wagnerlopes** [comment]
Fazfazerumamanutenção nos campos da tabela cidadao que precisam aumentar.

**Comment by wagnerlopes** [comment]
* Campo telefone aumentado para VARCHAR2(30), 30 caracteres alfnuméricos, no banco de dados.
* Na entidade CIDADAO é uma String Java;
