### ISSUE TITLE
Problemas para resolver na versao 5.1.13 do Sermilweb

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/sermilweb#3]
1) Termos e condicoes nao estah funcionando. O aceite ja vem checado para o usuario e mesmo se ele tirar o check, o checkbox volta selecionado de novo para ele na proxima pagina. Mas a validacao nao eh feita.

2) Kaptcha nao estah funcionando. O campo nao pode vir vazio mas o valor nao eh validado.

**Comment by wagnerlopes** [comment]
Nesta versão alpha 5.1.14 que comitei o aceite está funcionando no meu ambiente local de desenvolvimento.
O kaptcha quero ver o log em funcionamento no servidor de produção para saber porque só funciona no ambiente local.

**Comment by 6975usa** [comment]
Ok 
Coloquei o log do kaptcha a nivel error.
Vamos ver se ele aparece no link  Painel->Arquivos do sistema->Arquvo de Log

**Comment by wagnerlopes** [comment]
Fiz um alistamento online teste mas não recebi nenhum e-mail de resposta e o Log4j também não mandou e-mail para mim. Será que o SMTP não está funcionando corretamente?

**Comment by 6975usa** [comment]
Nao sei como monitorar o SMTP do servidor .

temos com certeza que rever o modo como o log está sendo feito.

2015-04-29 10:34 GMT-03:00 Wagner Lopes <notifications@github.com>:
