### ISSUE TITLE
Link de criação de CPF ao lado do alistamneto on-line.

### ISSUE THREAD

**Issue by raseng** [SERMIL/sermilweb#41]
Pode ser inserido um atalho (Receita Federal - https://www.receita.fazenda.gov.br/Aplicacoes/SSL/ATCTA/CPF/InscricaoPublica/inscricao.asp) para o cidadão fazer seu CPF on-line, a fim  de alistar-se?

**Comment by wagnerlopes** [comment]
Vou incluir o link e ver em qual página do alistamento fica melhor a posição do link de acesso da Receita.

**Comment by wagnerlopes** [comment]
Incluído na próxima versão.
