### ISSUE TITLE
Busca CEP nao funciona para alguns CEPs validos

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/sermilweb#5]
To abrindo esse problema(issue) so pra lembrar de coisas que precisamos fazer.
Quando resolvermos esse problema, podemos deletar esse issue.

Sobre o problema em si, provavelmente a tabela do cara ta desatualizada

**Comment by wagnerlopes** [comment]
Gostaria de saber se conseguimos acesso às tabelas do EBCORP relativas ao CEP.
Queria implementar as tabelas no modelo para substituir o acesso ao webservice externo que estamos usando por um esquema interno sob nosso controle.

**Comment by wagnerlopes** [comment]
Está implementado o acesso às tabelas do schema Correios do EBCorp. Foram criados sinônimos locais no schema do sermil, 14 ao todo, que fornecem acesso ao endereçamento postal.
Criei uma Materialized View associando as tabelas LOG_LOGRADOURO e LOG_LOCALIDADE que chamei de CEP, com código, logradouro, bairro, município e UF.

**Comment by wagnerlopes** [comment]
Implementada pesquisa de CEP no EBCORP.
